### ISSUE TITLE
TypeScript Error:  Top-level declarations in .d.ts files must start with either a 'declare' or 'export' modifier.

### ISSUE THREAD

**Issue by kilianc** [stephenmathieson/node-tlds#11]
```tsc --noEmit
node_modules/tlds/index.d.ts:1:1 - error TS1046: Top-level declarations in .d.ts files must start with either a 'declare' or 'export' modifier.

1 const tlds: string[];
  ~~~~~


Found 1 error.```

**Comment by Richienb** [comment]
Typings will be fixed in the next version. preview: https://github.com/stephenmathieson/node-tlds/blob/new/index.d.ts

**Comment by ryanbowden** [comment]
Why has this been closed when it has not been fixed and released?

**Comment by Richienb** [comment]
The fix exists in code at the moment but hasn't been released yet since it will ship as part of the automatic releases by the new cron job. However, I'll reopen this issue anyways.

**Comment by Yggdrasilqh** [comment]
Is there any way to fix this before release?

**Comment by Richienb** [comment]
@Yggdrasilqh You can manually define the types.

**Comment by benjie** [comment]
Before the release you can solve this with the following:

Create a `tlds.d.ts` file somewhere:

```ts
declare module "tlds" {
  const tlds: string[];
  export default tlds;
}
```

Tell TypeScript to replace the `tlds` built in types with your new file using the `paths` feature in `tsconfig.json`:

```jsonc
// tsconfig.json
{
  "compilerOptions": {
...
    "paths": {
      "tlds": ["custom_typings/tlds.d.ts"]
    }
  }
...
}
```

**Comment by Yggdrasilqh** [comment]
@benjie Better than add `"skipLibCheck": true` I added before 🍻

**Comment by dminkovsky** [comment]
Why not release this?

**Comment by Richienb** [comment]
@Richienb Good question. I've been putting off the cron job refactor but it will eventually ship v2.
