### ISSUE TITLE
New Cron Job Tracking Issue

### ISSUE THREAD

**Issue by Richienb** [stephenmathieson/node-tlds#12]
Development for this is on https://github.com/stephenmathieson/node-tlds/tree/new.

cc @stephenmathieson

**Comment by Richienb** [comment]
@stephenmathieson In order for GitHub to work with releases and NPM, please set the tokens in the secrets section of the repository settings.

Also, my NPM username appears to be with a lowercase so `npm owner add richienb tlds` should work.

**Comment by Richienb** [comment]
@stephenmathieson

**Comment by Richienb** [comment]
@stephenmathieson

**Comment by Richienb** [comment]
@stephenmathieson

**Comment by stephenmathieson** [comment]
Added you on npm!

**Comment by Richienb** [comment]
@stephenmathieson Great! I'll continue setting up the GitHub action.

**Comment by stephenmathieson** [comment]
Sounds good, thanks!

**Comment by Richienb** [comment]
@stephenmathieson The new cron job on GitHub actions is almost complete! Since you are the repository owner, you are the only person who can access and change secret environmental variables. Please follow [this guide](https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#creating-encrypted-secrets-for-a-repository) to add an `NPM_TOKEN` so that the automatic deployment will work.

**Comment by stephenmathieson** [comment]
Cool ok, thanks for setting this up! I'll try to get a user/token setup specifically for publishing this package soon.

**Comment by Richienb** [comment]
Please also add a `GITHUB_TOKEN` so that the cron job is able to commit the new changelog and create new release tags.

**Comment by stephenmathieson** [comment]
We should use the built-in token and just commit as the actions not.

I created a new npm user for this. Waiting on publishing rights to propagate, then will add the token here.

**Comment by stephenmathieson** [comment]
Just added `NPM_TOKEN` and verified the user has publish access:

```
➜  node-tlds git:(master) npm info tlds

tlds@1.208.0 | MIT | deps: none | versions: 207

[ ... ]

dist-tags:
latest: 1.208.0

published a minute ago by tlds-bot 
```

Let me know if you need anything else.
