### ISSUE TITLE
Second level domains

### ISSUE THREAD

**Issue by AdriVanHoudt** [stephenmathieson/node-tlds#4]
How hard would it be to also include second level domains? Scraped from https://publicsuffix.org/list/public_suffix_list.dat for example

**Comment by taskinosman** [comment]
there are many maintained repors for that publicsuffix around, especially for JS

**Comment by stephenmathieson** [comment]
There are no plans on adding second level domains here. Thank you for the suggestion tho!

**Comment by TooTallNate** [comment]
You probably want https://www.npmjs.com/package/psl.
